version: '2'
services:
        nginx:
             build: ./nginx/
             volumes:
                  - ./nginx/www/:/var/www/nginx
             networks:
                  - se_backend
        grproxy:
             build: ./grproxy/
             ports: 
                  - 8080:8080
             networks:
                  - se_frontend
                  - se_backend

        hbase:
             build: ./hbase/
             ports:
                  - 16010:16010
                  #- 16301:16301
                  #- 9095:9095
                  - 8085:8085
                  - 2181:2181
             networks:
                  #- se_backend
                  se_backend:
                      aliases:
                           - zookeeper  
        gserve1:
             build: ./gserve/
             environment:
                 - servername=gserve1
             networks:
                  - se_backend
        gserve2:
             build: ./gserve/
             environment:
                 - servername=gserve2
             networks:
                 - se_backend
networks:
     se_frontend:
        driver: bridge
     se_backend:
        driver: bridge


            
