version: '2'
services:
        nginx:
             build: ./nginx/
             ports: 
                  - 6060:80
             volumes:
                  - ./nginx/www/:/var/www/nginx
             
